const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const postsDir = path.join(root, 'posts');
const assetsDir = path.join(root, 'assets');
const siteUrl = 'https://tiyunclub.com';

const keywordTags = [
  ['IPLC', /\bIPLC\b/i], ['IEPL', /\bIEPL\b/i], ['ChatGPT', /ChatGPT/i],
  ['Claude', /Claude/i], ['Netflix', /Netflix/i], ['Disney+', /Disney\+/i],
  ['TikTok', /TikTok/i], ['游戏加速', /游戏|区服/], ['Clash', /Clash/i],
  ['Sing-box', /Sing-box/i], ['Shadowrocket', /Shadowrocket|小火箭/i],
  ['网络诊断', /测速|丢包|延迟|ping|诊断/i]
];

function parseFrontMatter(source) {
  const match = source.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*\r?\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: source };
  const meta = {};
  match[1].split(/\r?\n/).forEach((line) => {
    const separator = line.indexOf(':');
    if (separator < 0) return;
    const key = line.slice(0, separator).trim();
    meta[key] = line.slice(separator + 1).trim().replace(/^['"]|['"]$/g, '');
  });
  return { meta, body: match[2] };
}

function textLength(markdown) {
  return markdown
    .replace(/```[\s\S]*?```/g, '')
    .replace(/<[^>]+>|[#*|>`\[\]()_-]/g, '')
    .replace(/\s/g, '').length;
}

function escapeXml(value) {
  return String(value).replace(/[<>&'"]/g, (char) => ({ '<':'&lt;', '>':'&gt;', '&':'&amp;', "'":'&apos;', '"':'&quot;' })[char]);
}

const posts = fs.readdirSync(postsDir)
  .filter((name) => /^\d{2}-.+\.md$/.test(name))
  .map((file) => {
    const source = fs.readFileSync(path.join(postsDir, file), 'utf8');
    const { meta, body } = parseFrontMatter(source);
    const slug = file.replace(/\.md$/, '');
    const searchText = `${meta.title || ''} ${meta.category || ''} ${body}`;
    const tags = [meta.category, ...keywordTags.filter(([, pattern]) => pattern.test(searchText)).map(([tag]) => tag)]
      .filter(Boolean).filter((tag, index, all) => all.indexOf(tag) === index).slice(0, 5);
    return {
      source: file,
      slug,
      title: meta.title || slug,
      description: meta.description || '',
      date: meta.date || '1970-01-01',
      category: meta.category || '文章',
      tags,
      body,
      readingMinutes: Math.max(5, Math.ceil(textLength(body) / 350)),
      url: `article.html?post=${encodeURIComponent(slug)}`
    };
  })
  .sort((a, b) => b.date.localeCompare(a.date) || a.source.localeCompare(b.source));

fs.mkdirSync(assetsDir, { recursive: true });
fs.writeFileSync(
  path.join(assetsDir, 'posts-data.js'),
  `// Generated by scripts/build-content.js. Do not edit manually.\nwindow.TIYUN_POSTS = ${JSON.stringify(posts, null, 2)};\n`,
  'utf8'
);

const rssItems = posts.map((post) => `  <item>\n    <title>${escapeXml(post.title)}</title>\n    <link>${siteUrl}/${escapeXml(post.url)}</link>\n    <guid>${siteUrl}/${escapeXml(post.url)}</guid>\n    <pubDate>${new Date(`${post.date}T00:00:00+08:00`).toUTCString()}</pubDate>\n    <description>${escapeXml(post.description)}</description>\n  </item>`).join('\n');
fs.writeFileSync(path.join(root, 'feed.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel>\n  <title>梯云社 / TIYUN CLUB</title>\n  <link>${siteUrl}/</link>\n  <description>网络节点评测、工具教程与网络诊断。</description>\n${rssItems}\n</channel></rss>\n`, 'utf8');

const staticPages = [
  '', 'knowledge.html', 'tools.html', 'airports.html',
  'airport-topic.html?topic=stable', 'airport-topic.html?topic=value',
  'airport-topic.html?topic=premium', 'airport-topic.html?topic=budget',
  'airport-topic.html?topic=payg', 'airport-topic.html?topic=discounts',
  'airport-topic.html?topic=trials', 'disclaimer.html'
];
const sitemapUrls = [...staticPages.map((url) => `${siteUrl}/${url}`), ...posts.map((post) => `${siteUrl}/${post.url}`)]
  .map((url) => `  <url><loc>${escapeXml(url)}</loc></url>`).join('\n');
fs.writeFileSync(path.join(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapUrls}\n</urlset>\n`, 'utf8');

console.log(`Built ${posts.length} posts, assets/posts-data.js, feed.xml and sitemap.xml.`);
